namespace SharpVoronoiLib.Exceptions;

public class VoronoiSiteGenerationProducedWrongCount() 
    : Exception("The number of sites generated by the point generation algorithm does not match the number of sites requested.");