using System;

namespace SharpVoronoiLib.Exceptions;

public class VoronoiSiteSkippedAsDuplicateException() 
    : Exception("This site was skipped during tessellation because it duplicates another site. " +
                "If sites are not generated by the library and may contain duplicates, " +
                "you must handle duplicates yourself and either not generate duplicates or skip these sites afterwards. " +
                "Note that handling duplicate sites is not well-defined for tesselation algorithms in practice. " +
                "For the purpose of this library and from standard practice, duplicate sites can be considered collapsed/merged with their original.");

// Note that we can theoretically include the same cell data for a duplicate site as for the original site.
// A purely mathematical result is possible - duplicate sites would have the same cell.
// But this would require the implementation to actually handle duplicate cells, edges, points, etc.
// In other words, if the implementation does not handle initial duplicates, then handling duplicates later is way more complicated.
// So the default practice for libraries dealing with this is to simply skip/merge duplicates.