name: Nuget Publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '5.0.x' ]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Publish FluentEmail.Core
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PACKAGE_NAME: VoronoiLib
          
          PROJECT_FILE_PATH: VoronoiLib/VoronoiLib.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
      - name: Publish package
        run: exit 0